[data_extraction]
# 数据列
# 100steps
# step_numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# 50steps
# step_numbers = [5, 10, 15, 20, 25, 30, 35, 40, 45]
# 10steps
step_numbers = []

[data_extraction.keys_of_rows]
#isotope = ["10010   H1", "1112990 Pseudo"]
isotope = ["Nuclide Density", "Total  "]
radioactivity = ["Radioactivity", "Total  "]
absorption = ["Absorption", "Total  "]
fission = ["Fission", "Total  "]
decay_heat = ["Decay Heat", "Total  "]
gamma_spectra = ["Gamma-ray", "Total  "]
#all = ["NucID", "Energy", "Total  "]
all = ["Nuclide Density", "Radioactivity", "Absorption", "Fission", "Decay Heat", "Gamma-ray", "Total  "]

[data_extraction.keys_of_column]
id = "NucId"
name = "Nuc_Name"


[file_path]
test_file_path = "./test"
burnup_time_file_path = "./burnup time"


[database]

[database.mysql]
user = "user"
password = "password"
url = "localhost"
port = 3306
dbname = "db"

[database.postgresql]
user = "user"
password = "password"
url = "localhost"
port = 5432
dbname = "db"


[nuclide_list]
# Np237 衰变链核素
decay = ['Np237', 'Pa233', 'U233', 'Th229', 'Ra225', 'Ac225', 'Fr221', 'At217', 'Bi213', 'Po213', 'Tl209', 'Pb209', 'Bi209', 'Tl205']
# UO2 裂变产物及轻核
fission_light = ['Se79', 'Kr83', 'Sr90', 'Y91', 'Zr94', 'Mo95', 'Tc99', 'Ru101', 'Ag109', 'Sn126', 'I129', 'Xe136', 'Cs133', 'Ba138', 'La139', 'Ce142', 'Pr144', 'Nd144', 'Sm147', 'Eu153', 'Gd155', 'U234', 'U235', 'U236', 'U238', 'Np237', 'Pu239', 'Am241', 'Am242', 'Cm242', 'Cm244']
# short-lives nuclide, 燃耗主要核素，重点观察Cs134、Cm242、Cm244，短寿核素，尤其是第一燃耗步结果
short_lives = ['Kr85', 'Kr85m1', 'Kr87', 'Kr88', 'Xe131m1', 'Xe133', 'Xe133m1', 'Xe135', 'Xe135m1', 'I130', 'I131', 'I132', 'I133', 'I134', 'I135', 'Rb86', 'Cs134', 'Cs136', 'Cs137', 'Cs138', 'Sb127', 'Te127', 'Te127m1', 'Te131m1', 'Te132', 'Mo99', 'Tc99m1', 'Ru103', 'Ru105', 'Rh105', 'Ru106', 'Sr89', 'Sr90', 'Sr91', 'Sr92', 'Ba139', 'Ba140', 'Ce141', 'Ce143', 'Ce144', 'Pu238', 'Pu239', 'Pu240', 'Pu241', 'Np239', 'Y90', 'Y91', 'Y92', 'Y93', 'Zr95', 'Nb95', 'Zr97', 'La140', 'La141', 'La142', 'Pr143', 'Nd147', 'Am241', 'Cm242', 'Cm244']
