version: '3.9'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data