version: '3.9'
services:
  mysql_db:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    environment:
      # Password for root access
      # - MYSQL_ROOT_PASSWORD=rootpassword
      # - MYSQL_ROOT_HOST=%
      
      - MYSQL_DATABASE=db
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=user
      # You can use whatever password you like
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/my.conf.d
